version: '2'
exclude_patterns:
- ".git/"
- "**.gif"
- "**.html"
- "**.json"
- "**.png"
- "**.svg"
- "**.xml"
- "**.yaml"
- "**.yml"
- app/assets/javascripts/dhtmlx*/
- config/dictionary_strings.rb
- config/model_attributes.rb
- config/yaml_strings.rb
- db/schema.rb
- db/schema.yml
- db/fixtures/**/*.yml
- db/migrate/20130923182042_collapsed_initial_migration.rb
- locale/
- public/javascripts/timeline/
- spec/
- test/
- tmp/
- vendor/assets/
checks:
  file-lines:
    config:
      threshold: 400
plugins:
  brakeman:
    enabled: false
  bundler-audit:
    enabled: false
  csslint:
    enabled: false
  duplication:
    enabled: true
    exclude_patterns:
    - app/decorators/
    - app/javascript/**/*.spec.js
    - app/javascript/**/*.schema.js
    config:
      concurrency: 1
      languages:
        ruby:
          mass_threshold: 30
        javascript:
  eslint:
    enabled: true
    channel: eslint-5
    checks:
      key-spacing:
        enabled: false
      no-undefined:
        enabled: false
      quotes:
        enabled: false
    config:
      ignore_warnings: true
      extensions:
      - ".js"
      - ".jsx"
  fixme:
    enabled: false
  markdownlint:
    enabled: false
  rubocop:
    enabled: true
    config: ".rubocop_cc.yml"
    channel: rubocop-1-56-3
  stylelint:
    enabled: true
prepare:
  fetch:
  - url: https://raw.githubusercontent.com/ManageIQ/manageiq-style/master/.rubocop_base.yml
    path: ".rubocop_base.yml"
  - url: https://raw.githubusercontent.com/ManageIQ/manageiq-style/master/.rubocop_cc_base.yml
    path: ".rubocop_cc_base.yml"
  - url: https://raw.githubusercontent.com/ManageIQ/manageiq-style/master/styles/base.yml
    path: styles/base.yml
  - url: https://raw.githubusercontent.com/ManageIQ/manageiq-style/master/styles/cc_base.yml
    path: styles/cc_base.yml
