GlobalVars:
  AllowedVariables:
  # Loggers
  - $audit_log
  - $api_log
  - $aws_log
  - $azure_log
  - $datawarehouse_log
  - $fog_log
  - $lenovo_log
  - $log
  - $miq_ae_logger
  - $policy_log
  - $rails_log
  - $rhevm_log
  - $kube_log
  - $mw_log
  - $scvmm_log
  - $vim_log
  - $websocket_log
  # In Automate methods
  - $evm
#
# Special Exclusions
#
AllCops:
  TargetRubyVersion: 2.2
