inherit_from:
- https://raw.githubusercontent.com/ManageIQ/guides/master/.rubocop_base.yml
# put all local rubocop config into .rubocop_local.yml as it will be loaded by .rubocop_cc.yml as well
- .rubocop_local.yml
