build:
  environment:
    node: v8.11.3
  dependencies:
    before:
    - sudo apt-get -y install cmake;
    - git clone https://github.com/manageiq/manageiq.git spec/manageiq;
  tests:
    override:
      -
        command: "true"
  nodes:
    analysis:
      environment:
        node: v8.11.3
      tests:
        override:
          -
            command: rubocop-run
            use_website_config: false
          - js-scrutinizer-run
