# yarn:install is a rails 5.1 task, webpacker:compile needs it
namespace :yarn do
  task :install do
    puts 'yarn:install called, not doing anything'
  end
end

# need the initializer for the rake tasks to work
require ManageIQ::UI::Classic::Engine.root.join('config/initializers/webpacker.rb')
unless Rake::Task.task_defined?("webpacker")
  load 'tasks/webpacker.rake'
  load 'tasks/webpacker/compile.rake'
  load 'tasks/webpacker/clobber.rake'
  load 'tasks/webpacker/verify_install.rake'         # needed by compile
  load 'tasks/webpacker/check_node.rake'             # needed by verify_install
  load 'tasks/webpacker/check_yarn.rake'             # needed by verify_install
  load 'tasks/webpacker/check_webpack_binstubs.rake' # needed by verify_install
end

namespace :webpack do
  paths_config = ManageIQ::UI::Classic::Engine.root.join('config/webpack/paths.json')

  file paths_config do |task|
    File.open(task.name, 'w') do |file|
      file.write(JSON.pretty_generate(
        :info    => "This file is autogenerated by rake webpack:paths, do not edit",
        :output  => Rails.root.to_s,
        :engines => asset_engines,
      ) + "\n")
    end
  end

  task :paths => paths_config
end
