export const serviceDialogResponse = [{
  dialog_tabs: [
    {
      href: 'http://localhost:3000/api/service_dialogs/1080',
      id: '1080',
      description: null,
      display: null,
      created_at: '2024-02-07T11:07:59Z',
      updated_at: '2024-02-07T11:07:59Z',
      label: 'New tab',
      display_method: null,
      display_method_options: null,
      dialog_id: '118',
      position: 0,
      dialog_groups: [
        {
          href: 'http://localhost:3000/api/service_dialogs/1209',
          id: '1209',
          description: null,
          display: null,
          created_at: '2024-02-07T11:07:59Z',
          updated_at: '2024-07-02T15:33:26Z',
          label: 'New section',
          display_method: null,
          display_method_options: null,
          dialog_tab_id: '1080',
          position: 0,
          dialog_fields: [
            {
              href: 'http://localhost:3000/api/service_dialogs/7542',
              id: '7542',
              name: 'text_box_1',
              description: '',
              data_type: null,
              notes: null,
              notes_display: null,
              display: 'edit',
              display_method: null,
              display_method_options: {},
              required: true,
              required_method: null,
              required_method_options: {},
              default_value: '',
              values: null,
              values_method: null,
              values_method_options: {},
              options: {
                protected: false,
                show_past_days: false,
                force_multi_value: false,
              },
              created_at: '2024-02-07T11:07:59.008Z',
              updated_at: '2024-07-02T15:33:26.693Z',
              label: 'Text Box',
              dialog_group_id: '1209',
              position: 0,
              validator_type: 'f',
              validator_rule: null,
              reconfigurable: false,
              dynamic: false,
              show_refresh_button: false,
              load_values_on_init: true,
              read_only: false,
              auto_refresh: false,
              trigger_auto_refresh: false,
              visible: true,
              validator_message: null,
              type: 'DialogFieldTextBox',
              resource_action: {
                action: null,
                resource_type: 'DialogField',
                ae_namespace: null,
                ae_class: null,
                ae_instance: null,
                ae_message: null,
                ae_attributes: {},
                configuration_script_id: null,
              },
              dialog_field_responders: [],
            },
            {
              href: 'http://localhost:3000/api/service_dialogs/7543',
              id: '7543',
              name: 'textarea_box_1',
              description: '',
              data_type: null,
              notes: null,
              notes_display: null,
              display: 'edit',
              display_method: null,
              display_method_options: {},
              required: true,
              required_method: null,
              required_method_options: {},
              default_value: '',
              values: null,
              values_method: null,
              values_method_options: {},
              options: {
                protected: false,
                show_past_days: false,
                force_multi_value: false,
              },
              created_at: '2024-02-07T11:07:59.052Z',
              updated_at: '2024-07-02T15:33:26.694Z',
              label: 'Text Area',
              dialog_group_id: '1209',
              position: 1,
              validator_type: 'f',
              validator_rule: null,
              reconfigurable: false,
              dynamic: false,
              show_refresh_button: false,
              load_values_on_init: true,
              read_only: false,
              auto_refresh: false,
              trigger_auto_refresh: false,
              visible: true,
              validator_message: null,
              type: 'DialogFieldTextAreaBox',
              resource_action: {
                action: null,
                resource_type: 'DialogField',
                ae_namespace: null,
                ae_class: null,
                ae_instance: null,
                ae_message: null,
                ae_attributes: {},
                configuration_script_id: null,
              },
              dialog_field_responders: [],
            },
            {
              href: 'http://localhost:3000/api/service_dialogs/7544',
              id: '7544',
              name: 'check_box_1',
              description: '',
              data_type: null,
              notes: null,
              notes_display: null,
              display: 'edit',
              display_method: null,
              display_method_options: {},
              required: true,
              required_method: null,
              required_method_options: {},
              default_value: '',
              values: null,
              values_method: null,
              values_method_options: {},
              options: {
                protected: false,
                show_past_days: false,
                force_multi_value: false,
              },
              created_at: '2024-02-07T11:07:59.079Z',
              updated_at: '2024-07-02T15:33:26.695Z',
              label: 'Check Box',
              dialog_group_id: '1209',
              position: 2,
              validator_type: null,
              validator_rule: null,
              reconfigurable: false,
              dynamic: false,
              show_refresh_button: false,
              load_values_on_init: true,
              read_only: false,
              auto_refresh: false,
              trigger_auto_refresh: false,
              visible: true,
              validator_message: null,
              type: 'DialogFieldCheckBox',
              resource_action: {
                action: null,
                resource_type: 'DialogField',
                ae_namespace: null,
                ae_class: null,
                ae_instance: null,
                ae_message: null,
                ae_attributes: {},
                configuration_script_id: null,
              },
              dialog_field_responders: [],
            },
            {
              href: 'http://localhost:3000/api/service_dialogs/7545',
              id: '7545',
              name: 'dropdown_list_1',
              description: '',
              data_type: 'string',
              notes: null,
              notes_display: null,
              display: 'edit',
              display_method: null,
              display_method_options: {},
              required: true,
              required_method: null,
              required_method_options: {},
              default_value: '16',
              values_method: null,
              values_method_options: {},
              options: {
                sort_by: 'description',
                sort_order: 'ascending',
                force_multi_value: false,
                show_past_days: false,
                protected: false,
              },
              created_at: '2024-02-07T11:07:59.083Z',
              updated_at: '2024-07-02T15:33:26.696Z',
              label: 'Dropdown',
              dialog_group_id: '1209',
              position: 3,
              validator_type: null,
              validator_rule: null,
              reconfigurable: false,
              dynamic: true,
              show_refresh_button: true,
              load_values_on_init: true,
              read_only: false,
              auto_refresh: false,
              trigger_auto_refresh: false,
              visible: true,
              validator_message: null,
              type: 'DialogFieldDropDownList',
              resource_action: {
                action: null,
                resource_type: 'DialogField',
                ae_namespace: 'Cloud/VM/Provisioning/StateMachines',
                ae_class: 'VMProvisioning_VM',
                ae_instance: 'VM_instance',
                ae_message: null,
                ae_attributes: {},
                configuration_script_id: null,
              },
              dialog_field_responders: [],
              values: [
                [
                  16,
                  '16GB',
                ],
                [
                  2,
                  '2GB',
                ],
                [
                  4,
                  '4GB',
                ],
              ],
            },
            {
              href: 'http://localhost:3000/api/service_dialogs/7546',
              id: '7546',
              name: 'dropdown_list_2_1',
              description: '',
              data_type: 'string',
              notes: null,
              notes_display: null,
              display: 'edit',
              display_method: null,
              display_method_options: {},
              required: true,
              required_method: null,
              required_method_options: {},
              default_value: '[]',
              values: [
                [
                  '1',
                  'One',
                ],
                [
                  '3',
                  'Three',
                ],
                [
                  '2',
                  'Two',
                ],
              ],
              values_method: null,
              values_method_options: {},
              options: {
                sort_by: 'description',
                sort_order: 'ascending',
                force_multi_value: true,
                show_past_days: false,
                protected: false,
              },
              created_at: '2024-02-07T11:07:59.087Z',
              updated_at: '2024-07-02T15:33:26.697Z',
              label: 'VisibileCheck DDL',
              dialog_group_id: '1209',
              position: 4,
              validator_type: null,
              validator_rule: null,
              reconfigurable: false,
              dynamic: false,
              show_refresh_button: false,
              load_values_on_init: true,
              read_only: false,
              auto_refresh: false,
              trigger_auto_refresh: false,
              visible: true,
              validator_message: null,
              type: 'DialogFieldDropDownList',
              resource_action: {
                action: null,
                resource_type: 'DialogField',
                ae_namespace: null,
                ae_class: null,
                ae_instance: null,
                ae_message: null,
                ae_attributes: {},
                configuration_script_id: null,
              },
              dialog_field_responders: [],
            },
            {
              href: 'http://localhost:3000/api/service_dialogs/7547',
              id: '7547',
              name: 'radio_button_1',
              description: '',
              data_type: 'string',
              notes: null,
              notes_display: null,
              display: 'edit',
              display_method: null,
              display_method_options: {},
              required: true,
              required_method: null,
              required_method_options: {},
              default_value: '',
              values: [
                [
                  '1',
                  'One',
                ],
                [
                  '2',
                  'Two',
                ],
                [
                  '3',
                  'Three',
                ],
              ],
              values_method: null,
              values_method_options: {},
              options: {
                sort_by: 'description',
                sort_order: 'ascending',
                show_past_days: false,
                protected: false,
                force_multi_value: false,
              },
              created_at: '2024-02-07T11:07:59.107Z',
              updated_at: '2024-07-02T15:33:26.698Z',
              label: 'Radio Button',
              dialog_group_id: '1209',
              position: 5,
              validator_type: null,
              validator_rule: null,
              reconfigurable: false,
              dynamic: false,
              show_refresh_button: false,
              load_values_on_init: true,
              read_only: false,
              auto_refresh: false,
              trigger_auto_refresh: false,
              visible: true,
              validator_message: null,
              type: 'DialogFieldRadioButton',
              resource_action: {
                action: null,
                resource_type: 'DialogField',
                ae_namespace: null,
                ae_class: null,
                ae_instance: null,
                ae_message: null,
                ae_attributes: {},
                configuration_script_id: null,
              },
              dialog_field_responders: [],
            },
            {
              href: 'http://localhost:3000/api/service_dialogs/7548',
              id: '7548',
              name: 'date_control_1',
              description: '',
              data_type: null,
              notes: null,
              notes_display: null,
              display: 'edit',
              display_method: null,
              display_method_options: {},
              required: true,
              required_method: null,
              required_method_options: {},
              default_value: '',
              values: null,
              values_method: null,
              values_method_options: {},
              options: {
                show_past_dates: false,
                show_past_days: false,
                protected: false,
                force_multi_value: false,
              },
              created_at: '2024-02-07T11:07:59.129Z',
              updated_at: '2024-07-02T15:33:26.699Z',
              label: 'Datepicker',
              dialog_group_id: '1209',
              position: 6,
              validator_type: null,
              validator_rule: null,
              reconfigurable: false,
              dynamic: false,
              show_refresh_button: false,
              load_values_on_init: true,
              read_only: false,
              auto_refresh: false,
              trigger_auto_refresh: false,
              visible: true,
              validator_message: null,
              type: 'DialogFieldDateControl',
              resource_action: {
                action: null,
                resource_type: 'DialogField',
                ae_namespace: null,
                ae_class: null,
                ae_instance: null,
                ae_message: null,
                ae_attributes: {},
                configuration_script_id: null,
              },
              dialog_field_responders: [],
            },
            {
              href: 'http://localhost:3000/api/service_dialogs/7550',
              id: '7550',
              name: 'tag_control_1',
              description: '',
              data_type: 'string',
              notes: null,
              notes_display: null,
              display: 'edit',
              display_method: null,
              display_method_options: {},
              required: true,
              required_method: null,
              required_method_options: {},
              default_value: null,
              values: [
                {
                  href: 'http://localhost:3000/api/service_dialogs/8',
                  id: '8',
                  name: 'active_directory',
                  description: 'Active Directory Server',
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/9',
                  id: '9',
                  name: 'application_servers',
                  description: 'Application Servers',
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/11',
                  id: '11',
                  name: 'dhcp',
                  description: 'DHCP Server',
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/10',
                  id: '10',
                  name: 'database',
                  description: 'Database',
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/7',
                  id: '7',
                  name: 'desktop',
                  description: 'Desktop',
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/12',
                  id: '12',
                  name: 'evm_appliance',
                  description: 'EVM Appliance',
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/14',
                  id: '14',
                  name: 'messaging',
                  description: 'Messaging',
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/15',
                  id: '15',
                  name: 'security',
                  description: 'Security',
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/13',
                  id: '13',
                  name: 'infrastructure',
                  description: 'Virtual Infrastructure Management',
                },
                {
                  href: 'http://localhost:3000/api/service_dialogs/170',
                  id: '170',
                  name: 'app',
                  description: 'app',
                },
              ],
              values_method: null,
              values_method_options: {},
              options: {
                category_id: '6',
                force_single_value: false,
                sort_by: 'description',
                sort_order: 'ascending',
                category_description: 'Workload',
                category_name: 'function',
                category_single_value: false,
                show_past_days: false,
                protected: false,
                force_multi_value: false,
              },
              created_at: '2024-02-07T11:07:59.137Z',
              updated_at: '2024-07-02T15:33:26.719Z',
              label: 'Tag Control',
              dialog_group_id: '1209',
              position: 8,
              validator_type: null,
              validator_rule: null,
              reconfigurable: false,
              dynamic: false,
              show_refresh_button: false,
              load_values_on_init: true,
              read_only: false,
              auto_refresh: false,
              trigger_auto_refresh: false,
              visible: true,
              validator_message: null,
              type: 'DialogFieldTagControl',
              resource_action: {
                action: null,
                resource_type: 'DialogField',
                ae_namespace: null,
                ae_class: null,
                ae_instance: null,
                ae_message: null,
                ae_attributes: {},
                configuration_script_id: null,
              },
              dialog_field_responders: [],
            },
          ],
        },
      ],
    },
  ],
}];
