export const TOGGLE_TAG_CATEGORY_CHANGE = 'UI-COMPONENTS_TOGGLE_TAG_CATEGORY_CHANGE';
export const TOGGLE_TAG_VALUE_CHANGE = 'UI-COMPONENTS_TOGGLE_TAG_VALUE_CHANGE';
export const DELETE_SET_TAG = 'UI-COMPONENTS_DELETE_SET_TAG';
export const ADD_SET_TAG = 'UI-COMPONENTS_ADD_SET_TAG';
