export const TOGGLE_TAG_CATEGORY_CHANGE = 'UI-COMPONENTS_TOGGLE_TAG_CATEGORY_CHANGE';
export const TOGGLE_TAG_VALUE_CHANGE = 'UI-COMPONENTS_TOGGLE_TAG_VALUE_CHANGE';
export const DELETE_ASSIGNED_TAG = 'UI-COMPONENTS_DELETE_ASSIGNED_TAG';
export const CHANGE_ASSIGNED_TAG = 'UI-COMPONENTS_CHANGE_ASSIGNED_TAG';
export const ADD_ASSIGNED_TAG = 'UI-COMPONENTS_ADD_ASSIGNED_TAG';
export const LOAD_STATE = 'UI-COMPONENTS_LOAD_STATE';
export const RESET_STATE = 'UI-COMPONENTS_RESET_STATE';
