const exampleTestData = {
  href: 'http://localhost:3000/api/tasks/436299',
  id: '436299',
  name: 'VmOrTemplate - Resultant Set of Policy, Event: [Login failed]',
  state: 'Finished',
  status: 'Ok',
  message: 'Task completed successfully',
  userid: '#<User:0x00007fe1cd9558d8>',
  created_on: '2021-12-16T16:33:59Z',
  updated_on: '2021-12-16T16:34:02Z',
  pct_complete: null,
  context_data: null,
  results: null,
  miq_server_id: '17',
  identifier: null,
  started_on: '2021-12-16T16:33:59Z',
  zone: null,
  task_results: [
    {
      href: 'http://localhost:3000/api/tasks/4680',
      id: '4680',
      name: 'ag_destroy_test',
      result: 'allow',
      profiles: [
        {
          href: 'http://localhost:3000/api/tasks/215',
          id: '215',
          name: '_mels_policy_profile',
          description: '_mels_policy_profile',
          set_type: 'MiqPolicySet',
          created_on: '2021-11-08T21:15:50Z',
          updated_on: '2021-12-01T20:30:51Z',
          guid: '3ab85381-9e81-4da0-b0d0-fcab34580cb2',
          read_only: null,
          set_data: null,
          mode: 'control',
          owner_type: null,
          owner_id: null,
          userid: null,
          group_id: null,
          result: 'allow',
          policies: [
            {
              href: 'http://localhost:3000/api/tasks/60',
              id: '60',
              name: 'e67b96a2-ac8f-4c7b-b6e6-2e11c94a0b75',
              description: '_mels_policy',
              created_on: '2021-11-08T21:11:47Z',
              updated_on: '2021-11-08T21:11:47Z',
              expression: null,
              towhat: 'Vm',
              guid: 'e67b96a2-ac8f-4c7b-b6e6-2e11c94a0b75',
              created_by: 'admin',
              updated_by: 'admin',
              notes: null,
              active: true,
              mode: 'control',
              read_only: null,
              result: 'allow',
              conditions: [
                {
                  href: 'http://localhost:3000/api/tasks/39',
                  id: '39',
                  name: '6cd82a89-172f-458e-b11c-5e7052e11875',
                  description: '_mels',
                  result: 'allow',
                  expression: {
                    INCLUDES: {
                      field: 'Vm-name',
                      value: 'test',
                    },
                    result: true,
                  },
                },
              ],
              actions: [
                {
                  href: 'http://localhost:3000/api/tasks/2',
                  id: '2',
                  name: 'log',
                  description: 'Generate log message',
                  result: 'allow',
                },
              ],
            },
            {
              href: 'http://localhost:3000/api/tasks/61',
              id: '61',
              name: 'b03efa9e-db49-467b-bf58-ee8a82cf60b5',
              description: '_luds_policy',
              created_on: '2021-11-18T21:08:19Z',
              updated_on: '2021-11-18T21:08:19Z',
              expression: {
                exp: {
                  INCLUDES: {
                    field: 'Vm-name',
                    value: 'luds',
                  },
                },
                context_type: null,
                col_details: null,
                ruby: null,
              },
              towhat: 'Vm',
              guid: 'b03efa9e-db49-467b-bf58-ee8a82cf60b5',
              created_by: 'admin',
              updated_by: 'admin',
              notes: null,
              active: true,
              mode: 'control',
              read_only: null,
              result: 'N/A',
              conditions: [],
              actions: [],
              scope: {
                INCLUDES: {
                  field: 'Vm-name',
                  value: 'luds',
                },
                result: false,
              },
            },
          ],
        },
        {
          href: 'http://localhost:3000/api/tasks/220',
          id: '220',
          name: '_luds_policy_profile',
          description: '_luds_policy_profile',
          set_type: 'MiqPolicySet',
          created_on: '2021-11-18T21:10:52Z',
          updated_on: '2021-12-01T20:30:51Z',
          guid: '63b19e39-a8e2-4050-b25f-a55764cff273',
          read_only: null,
          set_data: null,
          mode: 'control',
          owner_type: null,
          owner_id: null,
          userid: null,
          group_id: null,
          result: 'N/A',
          policies: [
            {
              href: 'http://localhost:3000/api/tasks/61',
              id: '61',
              name: 'b03efa9e-db49-467b-bf58-ee8a82cf60b5',
              description: '_luds_policy',
              created_on: '2021-11-18T21:08:19Z',
              updated_on: '2021-11-18T21:08:19Z',
              expression: {
                exp: {
                  INCLUDES: {
                    field: 'Vm-name',
                    value: 'luds',
                  },
                },
                context_type: null,
                col_details: null,
                ruby: null,
              },
              towhat: 'Vm',
              guid: 'b03efa9e-db49-467b-bf58-ee8a82cf60b5',
              created_by: 'admin',
              updated_by: 'admin',
              notes: null,
              active: true,
              mode: 'control',
              read_only: null,
              result: 'N/A',
              conditions: [],
              actions: [],
              scope: {
                INCLUDES: {
                  field: 'Vm-name',
                  value: 'luds',
                },
                result: false,
              },
            },
          ],
        },
        {
          href: 'http://localhost:3000/api/tasks/223',
          id: '223',
          name: '_john_policy_profile',
          description: '_john_policy_profile',
          set_type: 'MiqPolicySet',
          created_on: '2021-12-06T21:22:27Z',
          updated_on: '2021-12-07T17:57:40Z',
          guid: '7ad125ee-7947-4215-a578-c0ade405fd87',
          read_only: null,
          set_data: null,
          mode: 'control',
          owner_type: null,
          owner_id: null,
          userid: null,
          group_id: null,
          result: 'N/A',
          policies: [
            {
              href: 'http://localhost:3000/api/tasks/62',
              id: '62',
              name: '5db0e6d8-89b4-4984-8907-45e9e8fe1049',
              description: '_johnPolicy',
              created_on: '2021-12-06T21:20:31Z',
              updated_on: '2021-12-06T21:20:31Z',
              expression: {
                exp: {
                  '=': {
                    field: 'Vm-active',
                    value: 'true',
                  },
                },
                context_type: null,
                col_details: null,
                ruby: null,
              },
              towhat: 'Vm',
              guid: '5db0e6d8-89b4-4984-8907-45e9e8fe1049',
              created_by: 'admin',
              updated_by: 'admin',
              notes: null,
              active: true,
              mode: 'control',
              read_only: null,
              result: 'N/A',
              conditions: [
                {
                  href: 'http://localhost:3000/api/tasks/41',
                  id: '41',
                  name: 'fb20c654-764c-46dc-a19f-6cda922222ea',
                  description: '_john',
                  scope: {
                    '=': {
                      count: 'Vm.disks',
                      value: '2',
                    },
                    result: false,
                  },
                  result: 'N/A',
                  expression: {
                    FIND: {
                      search: {
                        IS: {
                          field: 'Vm.advanced_settings-created_on',
                          value: 'Today',
                        },
                      },
                      checkany: {
                        '=': {
                          field: 'Vm.advanced_settings-name',
                          value: 'blue',
                        },
                      },
                    },
                  },
                },
              ],
              actions: [],
              scope: {
                '=': {
                  field: 'Vm-active',
                  value: 'true',
                },
                result: true,
              },
            },
          ],
        },
      ],
    },
  ],
  actions: [
    {
      name: 'delete',
      method: 'post',
      href: 'http://localhost:3000/api/tasks/436299',
    },
    {
      name: 'delete',
      method: 'delete',
      href: 'http://localhost:3000/api/tasks/436299',
    },
  ],
};

export default exampleTestData;
