name: Style linting
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pronto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: HeRoMo/pronto-action@v1.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
